### ISSUE TITLE
Rename also "geodo" to "geoget"?

### ISSUE THREAD

**Issue by jlandmann** [OGGM/geoget#2]
I'm working actually now on a clone created before the geodown name was changed to geoget and just updated  the origin URL for my git remote origin, no problem.
Once I've done the merging of my changes, should we also rename the downstream folder ('geodo', currently) and thus the internal imports to geoget? I've read somewhere in the Python packaging instructions that it's good practice to give the same name to the top-level directory and the one below (as it is done e.g. also in oggm).

**Comment by fmaussion** [comment]
Yes of course. we should be consistent everywhere! 

See oggm or salem for packaging basics.

**Comment by jlandmann** [comment]
Closing, as adressed in #4 and #5
